apiVersion: v1
description: A Helm chart to deploy the New Relic Php Agent as a daemonset
name: newrelic-php-agent
version: 1.0.0
appVersion: 1.0.0
home: https://hub.docker.com/r/newrelic/php-daemon
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
  - newrelic
  - apm
  - php
